apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drkiq-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drkiq
    spec:
      containers:
      - name: drkiq
        image: yaramohammed/drkiq
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: drkiq-config