apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drkiq-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drkiq
    spec:
      containers:
      - name: drkiq
        image: yaramohammed/drkiq
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /drkiq
          name: drkiq-src
        imagePullPolicy: Always
        env:
        - envFrom:
          - configMapRef:
              name: drkiq-config
#        - name: SECRET_TOKEN
#          value: asecuretokenwouldnormallygohere
#        - name: WORKER_PROCESSES
#          value: "1"
#        - name: LISTEN_ON
#          value: 0.0.0.0:8000
#        - name: DATABASE_URL
#          value: POSTGRES_SERVICE_HOST://drkiq:yourpassword@postgres:5432/drkiq?encoding=utf8&pool=5&timeout=5000
#        - name: CACHE_URL
#          value: REDIS_SERVICE_HOST://redis:6379/0
#        - name: JOB_WORKER_URL
#          value: REDIS_SERVICE_HOST://redis  
      volumes:
      - name: drkiq-src
        hostPath:
          path: /var/drkiq-src  

