apiVersion: batch/v1
kind: Job
metadata:
  name: db-job
spec:
  template:
    metadata:
      name: db-job
    spec:
      containers:
      - args:
        - rake
        - db:create
        env:
        - name: SECRET_TOKEN
          value: asecuretokenwouldnormallygohere
        - name: WORKER_PROCESSES
          value: "1"
        - name: LISTEN_ON
          value: 0.0.0.0:8000
        - name: DATABASE_URL
          value: postgres://drkiq:yourpassword@postgres:5432/drkiq?encoding=utf8&pool=5&timeout=5000
        - name: CACHE_URL
          value: redis://redis:6379/0
        - name: JOB_WORKER_URL
          value: redis://redis  
        image: yaramohammed/drkiq
        name: db-job
      restartPolicy: Never
